spring:
  datasource:
    url: jdbc:postgresql://77.237.244.113:5432/rentify_tools
    username: anton
    password: Anton_Ber_24!

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
key:
  access: ${ACCESS_KEY}
  refresh: ${REFRESH_KEY}

time:
  access: 7
  refresh: 30
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true